"use client";

import {
  createContext,
  useContext,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Language = "EN" | "CN";

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const cn = {
  Copy: "\u8907\u88fd",
  Copied: "\u5df2\u8907\u88fd",
  "View Token Info": "\u67e5\u770b\u4ee3\u5e63\u8cc7\u8a0a",
  "View on Solscan": "\u5728 Solscan \u67e5\u770b",
  "View Market": "\u67e5\u770b\u5e02\u5834",
  "View Liquidity Pool": "\u67e5\u770b\u6d41\u52d5\u6027\u6c60",
  "Open Solscan": "\u958b\u555f Solscan",
  "Open Birdeye": "\u958b\u555f Birdeye",
  "Open Dexscreener": "\u958b\u555f Dexscreener",
  "Open OKX DEX": "\u958b\u555f OKX DEX",
  "Open CoinMarketCap": "\u958b\u555f CoinMarketCap",
  Market: "\u5e02\u5834",
  Overview: "\u6982\u89bd",
  Token: "\u4ee3\u5e63",
  Notice: "\u63d0\u793a",
  FAQ: "\u5e38\u898b\u554f\u984c",
  "Official asset info": "\u5b98\u65b9\u8cc7\u7522\u8cc7\u8a0a",
  "MARKET DISPLAY": "\u5e02\u5834\u986f\u793a",
  "Pricing derived from external market activity.":
    "\u50f9\u683c\u4f86\u81ea\u5916\u90e8\u5e02\u5834\u6d3b\u52d5\u3002",
  "Market Context": "\u5e02\u5834\u80cc\u666f",
  Verification: "\u9a57\u8b49",
  "Mint first": "\u512a\u5148\u9a57\u8b49 Mint",
  "KSOL is an independent Solana token. Always verify the mint address before interacting.":
    "KSOL \u662f Solana \u4e0a\u7684\u7368\u7acb\u4ee3\u5e63\u8cc7\u7522\uff0c\u4e92\u52d5\u524d\u8acb\u52d9\u5fc5\u78ba\u8a8d Mint Address\u3002",
  "An independent token asset on Solana.":
    "Solana \u4e0a\u7684\u7368\u7acb\u4ee3\u5e63\u8cc7\u7522\u3002",
  "KSOL is designed as a transparent, verifiable on-chain asset with public explorer access and third-party market displays. Market data may vary depending on liquidity, trading activity, and external indexers.":
    "KSOL \u662f\u4e00\u500b\u53ef\u900f\u904e\u516c\u958b\u5340\u584a\u700f\u89bd\u5668\u67e5\u8a62\u7684\u93c8\u4e0a\u8cc7\u7522\uff0c\u4e26\u63d0\u4f9b\u7b2c\u4e09\u65b9\u5e02\u5834\u986f\u793a\u5165\u53e3\u3002\u5e02\u5834\u8cc7\u6599\u53ef\u80fd\u56e0\u6d41\u52d5\u6027\u3001\u4ea4\u6613\u6d3b\u8e8d\u5ea6\u8207\u5916\u90e8\u7d22\u5f15\u5668\u72c0\u614b\u800c\u4e0d\u540c\u3002",
  Chain: "\u93c8",
  "Mint Address": "\u4ee3\u5e63\u5730\u5740",
  "Liquidity Pair": "\u6d41\u52d5\u6027\u4ea4\u6613\u5c0d",
  Solana: "Solana",
  SOL: "SOL",
  "Token Information": "\u4ee3\u5e63\u8cc7\u8a0a",
  "Primary verification should start with the mint address.":
    "\u4e3b\u8981\u9a57\u8b49\u61c9\u5f9e Mint Address \u958b\u59cb\u3002",
  "Token Name": "\u4ee3\u5e63\u540d\u7a31",
  Network: "\u7db2\u8def",
  "Token Standard": "\u4ee3\u5e63\u6a19\u6e96",
  Decimals: "\u5c0f\u6578\u4f4d",
  Supply: "\u4f9b\u61c9\u91cf",
  "Primary Verification": "\u4e3b\u8981\u9a57\u8b49",
  "Market Data & Warning Notice": "\u5e02\u5834\u8cc7\u6599\u8207\u98a8\u96aa\u63d0\u793a",
  "KSOL may appear with caution or similarity warnings on some third-party wallets, DEX interfaces, or analytics platforms. These notices are generated by external systems and may be based on token name similarity, liquidity depth, trading history, metadata availability, or internal risk models.":
    "\u90e8\u5206\u7b2c\u4e09\u65b9\u9322\u5305\u3001DEX \u6216\u5206\u6790\u5e73\u53f0\u53ef\u80fd\u6703\u986f\u793a\u98a8\u96aa\u6216\u76f8\u4f3c\u540d\u7a31\u63d0\u793a\u3002\u9019\u985e\u63d0\u793a\u901a\u5e38\u7531\u5916\u90e8\u5e73\u53f0\u6839\u64da\u4ee3\u5e63\u540d\u7a31\u76f8\u4f3c\u5ea6\u3001\u6d41\u52d5\u6027\u6df1\u5ea6\u3001\u4ea4\u6613\u7d00\u9304\u3001metadata \u72c0\u614b\u6216\u5167\u90e8\u98a8\u63a7\u6a21\u578b\u7522\u751f\u3002",
  "KSOL does not claim to be SOL, does not represent native SOL, and should always be verified by its official mint address before any interaction.":
    "KSOL \u4e26\u4e0d\u5ba3\u7a31\u7b49\u540c\u65bc\u539f\u751f SOL\uff0c\u4e5f\u4e0d\u4ee3\u8868 Solana \u7684\u539f\u751f\u8cc7\u7522\u3002\u4f7f\u7528\u524d\u8acb\u4ee5\u5b98\u65b9 Mint Address \u4f5c\u70ba\u4e3b\u8981\u9a57\u8b49\u4f9d\u64da\u3002",
  "The official mint address should be treated as the primary identifier for KSOL. Token name, logo, or ticker alone should not be used for verification.":
    "\u5b98\u65b9 Mint Address \u61c9\u4f5c\u70ba\u8b58\u5225 KSOL \u7684\u4e3b\u8981\u4f9d\u64da\uff0c\u4e0d\u61c9\u53ea\u4f9d\u9760\u540d\u7a31\u3001Logo \u6216\u4ee3\u865f\u5224\u65b7\u3002",
  "Use external tools to verify KSOL's on-chain data and market activity. These platforms provide independent market displays and do not imply endorsement.":
    "\u4f7f\u7528\u5916\u90e8\u5de5\u5177\u67e5\u8a62 KSOL \u7684\u93c8\u4e0a\u8cc7\u6599\u8207\u5e02\u5834\u6d3b\u52d5\u3002\u9019\u4e9b\u5e73\u53f0\u50c5\u63d0\u4f9b\u7b2c\u4e09\u65b9\u5e02\u5834\u986f\u793a\uff0c\u4e0d\u4ee3\u8868\u80cc\u66f8\u6216\u4fdd\u8b49\u3002",
  "Verify token mint, holders, transfers, and on-chain metadata.":
    "\u67e5\u8a62\u4ee3\u5e63 Mint\u3001\u6301\u6709\u8005\u3001\u8f49\u5e33\u8207\u93c8\u4e0a metadata\u3002",
  "Market analytics and token activity reference.":
    "\u5e02\u5834\u5206\u6790\u8207\u4ee3\u5e63\u6d3b\u52d5\u53c3\u8003\u3002",
  "DEX pair display and trading surface.":
    "DEX \u4ea4\u6613\u5c0d\u5c55\u793a\u8207\u5e02\u5834\u4ecb\u9762\u3002",
  "Third-party DEX interface for swap routing.":
    "\u7b2c\u4e09\u65b9 DEX \u514c\u63db\u8def\u7531\u4ecb\u9762\u3002",
  "External market reference and token display.":
    "\u5916\u90e8\u5e02\u5834\u53c3\u8003\u8207\u4ee3\u5e63\u5c55\u793a\u9801\u3002",
  "View third-party market analytics and token activity.":
    "\u67e5\u770b\u7b2c\u4e09\u65b9\u5e02\u5834\u5206\u6790\u8207\u4ee3\u5e63\u6d3b\u52d5\u3002",
  "Check DEX pair data, liquidity, and trading activity.":
    "\u67e5\u770b DEX \u4ea4\u6613\u5c0d\u8cc7\u6599\u3001\u6d41\u52d5\u6027\u8207\u4ea4\u6613\u6d3b\u52d5\u3002",
  "Third-party DEX interface reference. Warning labels may appear depending on OKX's internal risk and token similarity rules.":
    "\u7b2c\u4e09\u65b9 DEX \u4ecb\u9762\u53c3\u8003\u3002OKX \u53ef\u80fd\u4f9d\u64da\u5176\u5167\u90e8\u98a8\u96aa\u8207\u4ee3\u5e63\u76f8\u4f3c\u6027\u898f\u5247\u986f\u793a\u63d0\u793a\u6a19\u7c64\u3002",
  "Liquidity Context": "\u6d41\u52d5\u6027\u80cc\u666f",
  "KSOL market pricing is determined by external DEX liquidity pools, trading activity, and third-party data indexers. Displayed price, market cap, volume, and warnings may vary across platforms.":
    "KSOL \u7684\u5e02\u5834\u50f9\u683c\u7531\u5916\u90e8 DEX \u6d41\u52d5\u6027\u6c60\u3001\u4ea4\u6613\u6d3b\u52d5\u8207\u7b2c\u4e09\u65b9\u8cc7\u6599\u7d22\u5f15\u5668\u6c7a\u5b9a\u3002\u4e0d\u540c\u5e73\u53f0\u986f\u793a\u7684\u50f9\u683c\u3001\u5e02\u503c\u3001\u6210\u4ea4\u91cf\u8207\u98a8\u96aa\u63d0\u793a\u53ef\u80fd\u4e0d\u540c\u3002",
  "Liquidity visibility depends on external pool depth, routing availability, and market activity.":
    "\u6d41\u52d5\u6027\u53ef\u898b\u5ea6\u53d6\u6c7a\u65bc\u5916\u90e8\u6c60\u6df1\u5ea6\u3001\u8def\u7531\u53ef\u7528\u6027\u8207\u5e02\u5834\u6d3b\u52d5\u3002",
  "For long-term reliability, users should verify:":
    "\u9577\u671f\u9a57\u8b49\u6642\uff0c\u5efa\u8b70\u4f7f\u7528\u8005\u78ba\u8a8d\uff1a",
  "Mint address": "Mint Address",
  "On-chain transfers": "\u93c8\u4e0a\u8f49\u5e33\u7d00\u9304",
  "Liquidity pair data": "\u6d41\u52d5\u6027\u6c60\u8cc7\u6599",
  "Holder distribution": "\u6301\u6709\u8005\u5206\u5e03",
  "Third-party market activity": "\u7b2c\u4e09\u65b9\u5e02\u5834\u6d3b\u52d5",
  "Is KSOL the same as SOL?": "KSOL \u548c SOL \u662f\u4e00\u6a23\u7684\u55ce\uff1f",
  "No. KSOL is an independent SPL token on Solana. It does not represent native SOL and should not be treated as SOL itself.":
    "\u4e0d\u662f\u3002KSOL \u662f Solana \u4e0a\u7684\u7368\u7acb SPL Token\uff0c\u4e26\u4e0d\u4ee3\u8868\u539f\u751f SOL\uff0c\u4e5f\u4e0d\u61c9\u88ab\u8996\u70ba SOL \u672c\u8eab\u3002",
  "Why do some platforms show a warning?":
    "\u70ba\u4ec0\u9ebc\u6709\u4e9b\u5e73\u53f0\u6703\u986f\u793a\u63d0\u793a\uff1f",
  "Third-party platforms may display caution labels based on token name similarity, liquidity, trading history, metadata, or their own risk models. Always verify the mint address before interacting.":
    "\u7b2c\u4e09\u65b9\u5e73\u53f0\u53ef\u80fd\u6839\u64da\u540d\u7a31\u76f8\u4f3c\u5ea6\u3001\u6d41\u52d5\u6027\u3001\u4ea4\u6613\u7d00\u9304\u3001metadata \u6216\u5167\u90e8\u98a8\u63a7\u6a21\u578b\u986f\u793a\u63d0\u793a\u3002\u4e92\u52d5\u524d\u8acb\u52d9\u5fc5\u78ba\u8a8d Mint Address\u3002",
  "Where should I verify KSOL?": "\u61c9\u8a72\u5728\u54ea\u88e1\u9a57\u8b49 KSOL\uff1f",
  "Use the mint address published on this site and verify through Solscan and other external market display tools.":
    "\u8acb\u4ee5\u672c\u7db2\u7ad9\u516c\u5e03\u7684 Mint Address \u70ba\u4e3b\uff0c\u4e26\u900f\u904e Solscan \u8207\u5176\u4ed6\u5916\u90e8\u5e02\u5834\u67e5\u8a62\u5de5\u5177\u4ea4\u53c9\u9a57\u8b49\u3002",
  "Is the price assured?": "\u50f9\u683c\u6703\u88ab\u627f\u8afe\u55ce\uff1f",
  "No. KSOL market price is determined by external liquidity and trading activity. This website does not provide assurances for price, liquidity, or third-party platform display status.":
    "\u4e0d\u662f\u3002KSOL \u7684\u5e02\u5834\u50f9\u683c\u7531\u5916\u90e8\u6d41\u52d5\u6027\u8207\u4ea4\u6613\u6d3b\u52d5\u6c7a\u5b9a\uff0c\u672c\u7db2\u7ad9\u4e0d\u627f\u8afe\u50f9\u683c\u3001\u6d41\u52d5\u6027\u6216\u7b2c\u4e09\u65b9\u5e73\u53f0\u986f\u793a\u72c0\u614b\u3002",
  "Market References": "\u5e02\u5834\u67e5\u8a62",
  Resources: "\u8cc7\u6e90",
  Legal: "\u6cd5\u52d9",
  "Token Info": "\u4ee3\u5e63\u8cc7\u8a0a",
  "Risk Notice": "\u98a8\u96aa\u63d0\u793a",
  "Official information and verification entry point for the KSOL token asset on Solana.":
    "Solana \u4e0a KSOL \u4ee3\u5e63\u8cc7\u7522\u7684\u5b98\u65b9\u8cc7\u8a0a\u8207\u9a57\u8b49\u5165\u53e3\u3002",
  "Disclaimer: Third-party platforms are independent references and do not imply endorsement.":
    "\u514d\u8cac\u8072\u660e\uff1a\u7b2c\u4e09\u65b9\u5e73\u53f0\u70ba\u7368\u7acb\u67e5\u8a62\u4f86\u6e90\uff0c\u4e0d\u4ee3\u8868\u80cc\u66f8\u3002",
};

const translations: Record<string, string> = cn;

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("EN");

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      t: (key) => (language === "CN" ? translations[key] ?? key : key),
    }),
    [language],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }

  return context;
}
